# Generated by Django 5.2 on 2025-05-16 13:17

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='🍎 Название продукта')),
                ('carbs_per_100g', models.FloatField(verbose_name='🥖 Углеводы на 100 г')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='🥣 Вес (г)')),
                ('carbs', models.FloatField(blank=True, null=True, verbose_name='🍬 Углеводы (г)')),
                ('xe', models.FloatField(blank=True, null=True, verbose_name='🍞 Хлебные единицы')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='📅 Дата')),
                ('time', models.TimeField(default=main.models.current_time, verbose_name='⏰ Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
