# Generated by Django 5.2 on 2025-05-03 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs_per_100g',
            field=models.FloatField(verbose_name='🥖 Углеводы на 100 г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='🍎 Название продукта'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приёма пищи')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время приёма пищи')),
                ('product_name', models.CharField(max_length=100, verbose_name='Продукт')),
                ('weight', models.FloatField(verbose_name='Вес (г)')),
                ('carbs', models.FloatField(verbose_name='Углеводы (г)')),
                ('xe', models.FloatField(verbose_name='ХЕ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
