# Generated by Django 5.2 on 2025-05-04 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_carbs_per_100g_alter_product_name_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
