# Generated by Django 5.2 on 2025-05-08 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_meal_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='product_name',
        ),
        migrations.AddField(
            model_name='meal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, null=True, verbose_name='🍬 Углеводы (г)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='📅 Дата'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='⏰ Время'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='weight',
            field=models.FloatField(verbose_name='🥣 Вес (г)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='xe',
            field=models.FloatField(blank=True, null=True, verbose_name='🍞 Хлебные единицы'),
        ),
    ]
