# Generated by Django 5.2 on 2025-05-08 17:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_meal_product_name_meal_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(default=main.models.current_time, verbose_name='⏰ Время'),
        ),
    ]
